### ISSUE TITLE
Login failure does not result in exception being thrown

### ISSUE THREAD

**Issue by micgro42** [lucaswerkmeister/m3api#29]
If login failed with the wrong password, I would expect an exception being thrown, similar to errors. However, the promise resolves and the code carries on.

This is the API response:
```
{
  login: {
    result: 'Failed',
    reason: {
      code: 'wrongpassword',
      text: 'Incorrect username or password entered. Please try again.'
    }
  }
}
```

**Comment by lucaswerkmeister** [comment]
Yes, the login API returns nonstandard errors :/ m3api-botpassword should handle this correctly (since 0.2.0), see https://github.com/lucaswerkmeister/m3api-botpassword/issues/1 / https://github.com/lucaswerkmeister/m3api-botpassword/commit/e4073bfd3e95ff423dedfcf20e5cc0d546fdef3c).

Although the `reason` in your response looks different… does it depend on the `errorformat`?

**Comment by lucaswerkmeister** [comment]
> Although the `reason` in your response looks different… does it depend on the `errorformat`?

Looks like it does, yeah. I should make the package handle that, at least.

**Comment by lucaswerkmeister** [comment]
I think this is done now, m3api-botpassword should handle this case correctly. (And I don’t think m3api itself should work around non-standard error formats in specific APIs that are only kept for backwards compatibility reasons.)
